var input = 'example1.cs';var compile_start = '3:10:13:777:340:400'; var lex_end = '3:10:13:778:301:400';var lex_elapsed = '0.000962';
var parse_end = '3:10:13:809:741:100';var parse_elapsed = '0.032434';
var error_recoverd = true;
var error_num = 11;
var errors = [];
errors.push({ line: 5, col : 21, msg: 'Bad IDENTIFIER 5Main'});
errors.push({ line: 16, col : 11, msg: 'Bad IDENTIFIER 2co'});
errors.push({ line: 3, col : 5, msg: 'syntax error, unexpected IDENTIFIER'});
errors.push({ line: 7, col : 17, msg: 'syntax error, unexpected [, expecting ('});
errors.push({ line: 7, col : 43, msg: 'syntax error, unexpected ], expecting )'});
errors.push({ line: 9, col : 13, msg: 'syntax error, unexpected FOREACH'});
errors.push({ line: 9, col : 20, msg: 'syntax error, unexpected [, expecting ('});
errors.push({ line: 9, col : 32, msg: 'syntax error, unexpected ], expecting )'});
errors.push({ line: 12, col : 13, msg: 'syntax error, unexpected }, expecting ;'});
errors.push({ line: 17, col : 14, msg: 'syntax error, unexpected IF, expecting IDENTIFIER or STAR'});
errors.push({ line: 22, col : 5, msg: 'syntax error, unexpected }, expecting "," or ;'});
